### ISSUE TITLE
Default UHD commands is not working

### ISSUE THREAD

**Issue by shahram-WINS** [pothosware/SoapyRemote#70]
Hi
Although I can use SoapySDRUtil --find="remote=myServer, driver=remote" command for communicating with the server but I can not use any of the default UHD commands as you mentioned in the wiki part. For instance none of these work:

uhd_find_devices --args="driver=remote,remote=myServer"
uhd_find_devices --args="driver=remote,remote=myServer,type=soapy"
uhd_find_devices --args="driver=remote,remote=myServer,remote:type=b200"

**Comment by guruofquality** [comment]
I suggest two things, double check the notes about "UHD_MODULE_PATH" in https://github.com/pothosware/SoapyUHD/wiki#soapy-devices-in-uhd, this can be important for UHD installs, since its not always very good about finding modules. I mentioned this to the developers before and did not get anywhere.

Just as a note be careful about multiple installs of the same package, some times this is the cause of issues and it can be painful to debug: https://github.com/pothosware/SoapySDR/wiki/ConfigGuide#avoid-simultaneous-installs

I dont have a lot of information to go on, so those are my best guesses. If you have an issue, lets take this up on the issue tracker for SoapyUHD: https://github.com/pothosware/SoapyUHD/issues/
